"""Add Stripe fields to Medilogic_Driver

Revision ID: 00bb513688ea
Revises: 02416f8ee455
Create Date: 2025-09-03 01:11:39.712257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bb513688ea'
down_revision: Union[str, Sequence[str], None] = '02416f8ee455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_international_applications_application_fee_payment'), 'international_applications', type_='foreignkey')
    op.add_column('medilogic_drivers', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('medilogic_drivers', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('medilogic_drivers', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.add_column('medilogic_drivers', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('fk_payments_application_id'), 'payments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_payments_application_id'), 'payments', 'international_applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_column('medilogic_drivers', 'cancel_at_period_end')
    op.drop_column('medilogic_drivers', 'stripe_price_id')
    op.drop_column('medilogic_drivers', 'stripe_subscription_id')
    op.drop_column('medilogic_drivers', 'stripe_customer_id')
    op.create_foreign_key(op.f('fk_international_applications_application_fee_payment'), 'international_applications', 'payments', ['application_fee_payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
