"""Make pin_entered nullable in delivery_confrimations

Revision ID: 061586d2b274
Revises: 05a501c89125
Create Date: 2026-01-06 11:32:39.703797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061586d2b274'
down_revision: Union[str, Sequence[str], None] = '05a501c89125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_confirmations', 'pin_entered',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_confirmations', 'pin_entered',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
