"""Add file_size & mime_type to documents

Revision ID: 061c53d67e3b
Revises: 5b4a6fe06a23
Create Date: 2025-09-11 16:38:18.196705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '061c53d67e3b'
down_revision: Union[str, Sequence[str], None] = '5b4a6fe06a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(), nullable=True))
    op.drop_column('incident_files', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_files', sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
