"""add requires_pin and requires_wtn to trips

Revision ID: 07915e73b2cd
Revises: 061586d2b274
Create Date: 2026-01-10 15:50:23.883778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07915e73b2cd'
down_revision: Union[str, Sequence[str], None] = '061586d2b274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('requires_pin', sa.Boolean(), nullable=True))
    op.add_column('trips', sa.Column('requires_wtn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'requires_wtn')
    op.drop_column('trips', 'requires_pin')
    # ### end Alembic commands ###
