"""Add organization profile fields

Revision ID: 113de2cfef4d
Revises: 1602d29beb87
Create Date: 2025-08-13 23:47:31.019993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '113de2cfef4d'
down_revision: Union[str, Sequence[str], None] = '1602d29beb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_statuses', 'audit_status',
               existing_type=postgresql.ENUM('pending', 'passed', 'failed', 'escalated', name='auditstatusenum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::auditstatusenum"))
    op.alter_column('compliance_statuses', 'last_audit_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('compliance_statuses', 'next_audit_due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_compliance_statuses_id'), table_name='compliance_statuses')
    op.add_column('notifications', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=True))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('address_line', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('waste_processing_capability', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('delivery_capacity', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('contact_person_name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('contact_person_role', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('organizations', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'longitude')
    op.drop_column('organizations', 'latitude')
    op.drop_column('organizations', 'contact_person_role')
    op.drop_column('organizations', 'contact_person_name')
    op.drop_column('organizations', 'delivery_capacity')
    op.drop_column('organizations', 'waste_processing_capability')
    op.drop_column('organizations', 'license_number')
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'address_line')
    op.drop_column('organizations', 'phone_number')
    op.drop_column('organizations', 'email')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'title')
    op.create_index(op.f('ix_compliance_statuses_id'), 'compliance_statuses', ['id'], unique=False)
    op.alter_column('compliance_statuses', 'next_audit_due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('compliance_statuses', 'last_audit_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('compliance_statuses', 'audit_status',
               existing_type=postgresql.ENUM('pending', 'passed', 'failed', 'escalated', name='auditstatusenum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::auditstatusenum"))
    # ### end Alembic commands ###
