"""Add trip_id foreign key to DriverLocationHistory

Revision ID: 192c7ace2235
Revises: 5b09974fde62
Create Date: 2025-07-23 11:54:52.115087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192c7ace2235'
down_revision: Union[str, Sequence[str], None] = '5b09974fde62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_location_history', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'driver_location_history', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver_location_history', type_='foreignkey')
    op.drop_column('driver_location_history', 'trip_id')
    # ### end Alembic commands ###
