"""Add application_fee_payment_id to InternationalApplication

Revision ID: 19c0b00fd8b7
Revises: 6d5e94a3927a
Create Date: 2025-09-02 17:06:33.126270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c0b00fd8b7'
down_revision: Union[str, Sequence[str], None] = '6d5e94a3927a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('international_applications', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('fk_application_fee_payment'), 'international_applications', type_='foreignkey')
    op.create_foreign_key(None, 'international_applications', 'payments', ['application_fee_payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'international_applications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_application_fee_payment'), 'international_applications', 'payments', ['application_fee_payment_id'], ['id'], ondelete='SET NULL')
    op.alter_column('international_applications', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
