"""Add updated_at to invoices

Revision ID: 33d1cd6d03a6
Revises: d280cd0f75c8
Create Date: 2025-11-17 08:10:48.705082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d1cd6d03a6'
down_revision: Union[str, Sequence[str], None] = 'd280cd0f75c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'updated_at')
    # ### end Alembic commands ###
