"""Add message to PendingApplication

Revision ID: 3ffcea660829
Revises: 427f957f049e
Create Date: 2025-07-29 13:25:33.791923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffcea660829'
down_revision: Union[str, Sequence[str], None] = '427f957f049e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_applications', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_applications', 'message')
    # ### end Alembic commands ###
