"""Add soft delete fields to users

Revision ID: 40289db61693
Revises: 75dc8218fdcc
Create Date: 2025-08-27 18:37:02.121436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40289db61693'
down_revision: Union[str, Sequence[str], None] = '75dc8218fdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deletion_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_reason')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
