"""Initial schema

Revision ID: 427f957f049e
Revises: ca810bb747e9
Create Date: 2025-07-29 07:03:33.822217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427f957f049e'
down_revision: Union[str, Sequence[str], None] = 'ca810bb747e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'regulator', name='pendingrole'), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('organization_type', sa.String(), nullable=True),
    sa.Column('regulated_country', sa.String(), nullable=True),
    sa.Column('regulated_state', sa.String(), nullable=True),
    sa.Column('regulated_region', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_applications_email'), 'pending_applications', ['email'], unique=True)
    op.create_index(op.f('ix_pending_applications_id'), 'pending_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_applications_id'), table_name='pending_applications')
    op.drop_index(op.f('ix_pending_applications_email'), table_name='pending_applications')
    op.drop_table('pending_applications')
    # ### end Alembic commands ###
