"""Add GPS to delivery confirmations

Revision ID: 4cc8c3199150
Revises: 9f85691fcbcb
Create Date: 2025-07-29 23:09:10.336652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc8c3199150'
down_revision: Union[str, Sequence[str], None] = '9f85691fcbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_confirmations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_confirmations', 'longitude')
    op.drop_column('delivery_confirmations', 'latitude')
    # ### end Alembic commands ###
