"""Add license_expiry_date and supported_waste_types to organizations

Revision ID: 4f2611a4ce69
Revises: eb6ee4a46b14
Create Date: 2025-08-20 12:15:53.315097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2611a4ce69'
down_revision: Union[str, Sequence[str], None] = 'eb6ee4a46b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('license_expiry', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('supported_waste_types', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'supported_waste_types')
    op.drop_column('organizations', 'license_expiry')
    # ### end Alembic commands ###
