"""unique driver availability per day

Revision ID: 5dd0b241c09c
Revises: 79d1c3e4c138
Create Date: 2026-02-23 08:58:17.363303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd0b241c09c'
down_revision: Union[str, Sequence[str], None] = '79d1c3e4c138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_driver_availability_driver_day', 'driver_availabilities', ['driver_id', 'day_of_week'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_driver_availability_driver_day', 'driver_availabilities', type_='unique')
    # ### end Alembic commands ###
