"""Add updated_at column to Invoice model

Revision ID: 5f75b35d2989
Revises: b043876365a2
Create Date: 2025-11-07 13:27:30.671011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f75b35d2989'
down_revision: Union[str, Sequence[str], None] = 'b043876365a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'updated_at')
    # ### end Alembic commands ###
