"""Added is_visible_to_regulator to Incident model

Revision ID: 6115736bc553
Revises: de6a057b42d8
Create Date: 2025-07-18 18:10:29.962867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6115736bc553'
down_revision: Union[str, Sequence[str], None] = 'de6a057b42d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
