"""Add digital signature fields to ChainOfCustody

Revision ID: 6def9e525b58
Revises: a60a0d870a07
Create Date: 2025-07-19 13:13:53.446038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6def9e525b58'
down_revision: Union[str, Sequence[str], None] = 'a60a0d870a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_of_custody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('pickup_confirmed', 'in_transit', 'delayed', 'handed_off', 'delivered', name='custodyeventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('signed_by', sa.String(), nullable=True),
    sa.Column('signature_image_url', sa.String(), nullable=True),
    sa.Column('signature_timestamp', sa.DateTime(), nullable=True),
    sa.Column('witness_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_of_custody_id'), 'chain_of_custody', ['id'], unique=False)
    op.add_column('incidents', sa.Column('severity', sa.Enum('low', 'moderate', 'critical', name='severitylevel'), nullable=False))
    op.add_column('incidents', sa.Column('escalated', sa.Boolean(), nullable=True))
    op.add_column('incidents', sa.Column('is_visible_to_regulator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'is_visible_to_regulator')
    op.drop_column('incidents', 'escalated')
    op.drop_column('incidents', 'severity')
    op.drop_index(op.f('ix_chain_of_custody_id'), table_name='chain_of_custody')
    op.drop_table('chain_of_custody')
    # ### end Alembic commands ###
