"""add is_deleted to trips

Revision ID: 846a67be1c17
Revises: 00bb513688ea
Create Date: 2025-09-06 22:40:31.129495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846a67be1c17'
down_revision: Union[str, Sequence[str], None] = '00bb513688ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_logs_trip_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'trips', ['trip_id'], ['id'], ondelete='SET NULL')
    op.add_column('trips', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_deleted')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_trip_id_fkey'), 'activity_logs', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###
