"""Add ICO registration and retention fields

Revision ID: 9498ef675114
Revises: d7c8dea570e6
Create Date: 2025-09-09 19:49:06.994498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9498ef675114'
down_revision: Union[str, Sequence[str], None] = 'd7c8dea570e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('ico_registration_number', sa.String(), nullable=True))
    op.add_column('pending_applications', sa.Column('organization_country', sa.String(), nullable=True))
    op.add_column('pending_applications', sa.Column('organization_state', sa.String(), nullable=True))
    op.add_column('pending_applications', sa.Column('organization_region', sa.String(), nullable=True))
    op.add_column('pending_applications', sa.Column('ico_registration_number', sa.String(), nullable=True))
    op.add_column('pending_applications', sa.Column('data_retention_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_applications', 'data_retention_years')
    op.drop_column('pending_applications', 'ico_registration_number')
    op.drop_column('pending_applications', 'organization_region')
    op.drop_column('pending_applications', 'organization_state')
    op.drop_column('pending_applications', 'organization_country')
    op.drop_column('organizations', 'ico_registration_number')
    # ### end Alembic commands ###
