"""add driver_credentials table and update documents

Revision ID: 9c3543189244
Revises: 113de2cfef4d
Create Date: 2025-08-18 14:15:11.807552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3543189244'
down_revision: Union[str, Sequence[str], None] = '113de2cfef4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('licence_number', sa.String(), nullable=False),
    sa.Column('licence_category', sa.String(), nullable=True),
    sa.Column('licence_expiry', sa.Date(), nullable=False),
    sa.Column('adr_certificate', sa.String(), nullable=True),
    sa.Column('adr_expiry', sa.Date(), nullable=True),
    sa.Column('cpc_certificate', sa.String(), nullable=True),
    sa.Column('cpc_expiry', sa.Date(), nullable=True),
    sa.Column('dbs_check', sa.String(), nullable=True),
    sa.Column('dbs_expiry', sa.Date(), nullable=True),
    sa.Column('medical_certificate', sa.String(), nullable=True),
    sa.Column('medical_expiry', sa.Date(), nullable=True),
    sa.Column('waste_training_cert', sa.String(), nullable=True),
    sa.Column('infection_control_cert', sa.String(), nullable=True),
    sa.Column('first_aid_cert', sa.String(), nullable=True),
    sa.Column('first_aid_expiry', sa.Date(), nullable=True),
    sa.Column('vehicle_insurance', sa.String(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('employment_contract', sa.String(), nullable=True),
    sa.Column('right_to_work_doc', sa.String(), nullable=True),
    sa.Column('right_to_work_expiry', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_credentials_id'), 'driver_credentials', ['id'], unique=False)
    op.add_column('documents', sa.Column('credential_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('revoked', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'documents', 'driver_credentials', ['credential_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'revoked')
    op.drop_column('documents', 'expiry_date')
    op.drop_column('documents', 'is_active')
    op.drop_column('documents', 'credential_id')
    op.drop_index(op.f('ix_driver_credentials_id'), table_name='driver_credentials')
    op.drop_table('driver_credentials')
    # ### end Alembic commands ###
