"""update user model

Revision ID: b3371c76414d
Revises: 4f2611a4ce69
Create Date: 2025-08-21 17:17:47.576031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3371c76414d'
down_revision: Union[str, Sequence[str], None] = '4f2611a4ce69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('license_expiry', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('regulated_waste_types', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('regulated_goods_types', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('regulated_logistics_scope', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'regulated_logistics_scope')
    op.drop_column('users', 'regulated_goods_types')
    op.drop_column('users', 'regulated_waste_types')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'license_expiry')
    op.drop_column('users', 'license_number')
    # ### end Alembic commands ###
