"""Add ico_registered to pending_applications

Revision ID: b3da736ec4c9
Revises: 9498ef675114
Create Date: 2025-09-10 09:49:37.641452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3da736ec4c9'
down_revision: Union[str, Sequence[str], None] = '9498ef675114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_applications', sa.Column('ico_registered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_applications', 'ico_registered')
    # ### end Alembic commands ###
