"""Add can_upload_docs to Medilogic_Driver

Revision ID: b8ed099ad05c
Revises: 5eea6e18f26c
Create Date: 2025-08-29 10:54:10.407184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ed099ad05c'
down_revision: Union[str, Sequence[str], None] = '5eea6e18f26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medilogic_drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('preferred_role', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'pending', 'approved', 'rejected', name='driverstatus'), nullable=False),
    #sa.Column('subscription_status', sa.Enum('active', 'expired', 'cancelled', 'none', name='subscriptionstatus'), nullable=False),
    sa.Column('subscription_plan', sa.Enum('free', 'green', 'blue', name='subscriptionplan'), nullable=False),
    #sa.Column('badge_type', sa.Enum('none', 'green', 'blue', name='badgetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('drivers_license', sa.String(), nullable=True),
    sa.Column('dvla_check_code', sa.String(), nullable=True),
    sa.Column('proof_of_id_address', sa.String(), nullable=True),
    sa.Column('mot_certificate', sa.String(), nullable=True),
    sa.Column('vehicle_insurance', sa.String(), nullable=True),
    sa.Column('waste_carrier_license', sa.String(), nullable=True),
    sa.Column('adr_certificate', sa.String(), nullable=True),
    sa.Column('dbs_check', sa.String(), nullable=True),
    sa.Column('professional_id_photo', sa.String(), nullable=True),
    sa.Column('can_view_analytics', sa.Boolean(), nullable=True),
    sa.Column('can_see_org_names', sa.Boolean(), nullable=True),
    sa.Column('can_upload_docs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medilogic_drivers_email'), 'medilogic_drivers', ['email'], unique=True)
    op.create_table('driver_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medilogic_driver_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medilogic_driver_id'], ['medilogic_drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('medilogic_driver_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'medilogic_drivers', ['medilogic_driver_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('medilogic_driver_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'payments', 'medilogic_drivers', ['medilogic_driver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'medilogic_driver_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'medilogic_driver_id')
    op.drop_table('driver_views')
    op.drop_index(op.f('ix_medilogic_drivers_email'), table_name='medilogic_drivers')
    op.drop_table('medilogic_drivers')
    # ### end Alembic commands ###
