"""Add testimonials table

Revision ID: ca810bb747e9
Revises: a48694900231
Create Date: 2025-07-26 18:41:39.110857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca810bb747e9'
down_revision: Union[str, Sequence[str], None] = 'a48694900231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_id'), 'testimonials', ['id'], unique=False)
    op.add_column('chain_of_custody', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chain_of_custody', 'organizations', ['organization_id'], ['id'])
    op.add_column('documents', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'documents', 'organizations', ['organization_id'], ['id'])
    op.add_column('driver_location_history', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'driver_location_history', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver_location_history', type_='foreignkey')
    op.drop_column('driver_location_history', 'organization_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'organization_id')
    op.drop_constraint(None, 'chain_of_custody', type_='foreignkey')
    op.drop_column('chain_of_custody', 'organization_id')
    op.drop_index(op.f('ix_testimonials_id'), table_name='testimonials')
    op.drop_table('testimonials')
    # ### end Alembic commands ###
