"""Add indexes and optional fields to support tables

Revision ID: d280cd0f75c8
Revises: 039a3f3fb5b3
Create Date: 2025-11-15 10:48:24.218766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd280cd0f75c8'
down_revision: Union[str, Sequence[str], None] = '039a3f3fb5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compliance_statuses', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_compliance_statuses_id'), 'compliance_statuses', ['id'], unique=False)
    op.add_column('support_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('support_messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_support_messages_organization_id'), 'support_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_messages_ticket_id'), 'support_messages', ['ticket_id'], unique=False)
    op.add_column('support_replies', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_support_replies_organization_id'), 'support_replies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_replies_ticket_id'), 'support_replies', ['ticket_id'], unique=False)
    op.add_column('support_tickets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_support_tickets_organization_id'), 'support_tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_organization_id'), table_name='support_tickets')
    op.drop_column('support_tickets', 'is_deleted')
    op.drop_index(op.f('ix_support_replies_ticket_id'), table_name='support_replies')
    op.drop_index(op.f('ix_support_replies_organization_id'), table_name='support_replies')
    op.drop_column('support_replies', 'updated_at')
    op.drop_index(op.f('ix_support_messages_ticket_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_organization_id'), table_name='support_messages')
    op.drop_column('support_messages', 'is_deleted')
    op.drop_column('support_messages', 'updated_at')
    op.drop_index(op.f('ix_compliance_statuses_id'), table_name='compliance_statuses')
    op.alter_column('compliance_statuses', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
