"""add pod_files table

Revision ID: d48d054038e9
Revises: b3da736ec4c9
Create Date: 2025-09-11 14:10:03.956252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48d054038e9'
down_revision: Union[str, Sequence[str], None] = 'b3da736ec4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_files_id'), 'pod_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pod_files_id'), table_name='pod_files')
    op.drop_table('pod_files')
    # ### end Alembic commands ###
