"""Added severity, location, escalation fields to incidents

Revision ID: de6a057b42d8
Revises: 9c870838d375
Create Date: 2025-07-18 18:03:21.460558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6a057b42d8'
down_revision: Union[str, Sequence[str], None] = '9c870838d375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('incident_type', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'location')
    op.drop_column('incidents', 'incident_type')
    # ### end Alembic commands ###
