"""Add pickup_at and dropoff_at to delivery_confirmations

Revision ID: e770ace1100f
Revises: 33d1cd6d03a6
Create Date: 2025-12-03 18:37:02.929505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e770ace1100f'
down_revision: Union[str, Sequence[str], None] = '33d1cd6d03a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_confirmations', sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('dropoff_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('external_client_name', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('external_client_email', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('external_client_signature_path', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('driver_signature_path', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('disposal_facility_name', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('disposal_facility_address', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('disposal_facility_signature_path', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('pickup_photo_path', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('dropoff_photo_path', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('extra_notes', sa.Text(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_confirmations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_delivery_confirmations_access_token'), 'delivery_confirmations', ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_confirmations_access_token'), table_name='delivery_confirmations')
    op.drop_column('delivery_confirmations', 'updated_at')
    op.drop_column('delivery_confirmations', 'created_at')
    op.drop_column('delivery_confirmations', 'token_expires_at')
    op.drop_column('delivery_confirmations', 'access_token')
    op.drop_column('delivery_confirmations', 'extra_notes')
    op.drop_column('delivery_confirmations', 'attachments')
    op.drop_column('delivery_confirmations', 'dropoff_photo_path')
    op.drop_column('delivery_confirmations', 'pickup_photo_path')
    op.drop_column('delivery_confirmations', 'disposal_facility_signature_path')
    op.drop_column('delivery_confirmations', 'disposal_facility_address')
    op.drop_column('delivery_confirmations', 'disposal_facility_name')
    op.drop_column('delivery_confirmations', 'driver_signature_path')
    op.drop_column('delivery_confirmations', 'external_client_signature_path')
    op.drop_column('delivery_confirmations', 'external_client_email')
    op.drop_column('delivery_confirmations', 'external_client_name')
    op.drop_column('delivery_confirmations', 'dropoff_at')
    op.drop_column('delivery_confirmations', 'pickup_at')
    # ### end Alembic commands ###
